title: MayStudio
description: Application Development Studio - Game & Application
author:
  name: MayStudio
  email: maystudiox@gmail.com

theme: minima

header_pages:
  - index.md
  - about.md

show_excerpts: true
